apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: occd-resources
  description: A collection of all OCCD Resources
spec:
  targets:
    - https://github.com/prabhu-sunderaraman/for-backstage-sample-service/blob/master/resource-pool-eventhub.yml