apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: occd-components
  description: A collection of all OCCD services
spec:
  targets:
    - https://github.com/prabhu-sunderaraman/for-backstage-sample-service/blob/master/resource-pool-consumer.yml
    - https://github.com/prabhu-sunderaraman/for-backstage-sample-library/blob/master/capacity-common-library.yml