apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: sample-apis
  description: A collection of all Sample APIs
spec:
  targets:
    - https://github.com/prabhu-sunderaraman/for-backstage-sample-service/blob/master/resource-pool-eventhub.yml